Royality/src/WebUI/Models/AutoAnbunViewModel.cs
using Royality.Application.Common.Models;
using System.Collections.Generic;

namespace Royality.WebUI.Models
{
    public class AutoAnbunViewModel
    {
        public AnbunSetting AnbunSetting { get; set; }
        public List<UriageInfo> UriageInfoList { get; set; }
    }
}

Royality/src/WebUI/Models/DenDetailInfoViewModel.cs
using Royality.Application.DenpyoItems.Queries.GetDenpyoInfo;

namespace Royality.WebUI.Models
{
    /// <summary>
    /// Den Detail Info
    /// </summary>
    public class DenDetailInfoViewModel
    {
        #region Property
        public DenpyoInfo DenpyoInfo { get; set; }
        public int? HinbanCount { get; set; }
        public bool? IsAnbunResultSet { get; set; }
        public bool IsNewDenpyo { get; set; }
        #endregion
    }
}

Royality/src/WebUI/Models/DenpyoListViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Royality.Models
{
    public class DenpyoListViewModel
    {
        #region Property
        public SelectList StatusList { get; set; }
        #endregion
    }
}

Royality/src/WebUI/Models/ErrorViewModel.cs
using System;

namespace Royality.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Royality/src/WebUI/Models/Response.cs
namespace Royality.WebUI.Models
{
    public class Response
    {
        public object Result { get; set; }
    }
}

Royality/src/WebUI/Controllers/BaseController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace Royality.WebUI.Controllers
{
    public abstract class BaseController : Controller
    {
        #region Private Member
        protected readonly IMediator _mediator;
        #endregion

        #region Controller
        /// <summary>
        /// Controller
        /// </summary>
        /// <param name="mediator"></param>
        public BaseController(IMediator mediator)
        {
            _mediator = mediator;
        }
        #endregion
    }
}

Royality/src/WebUI/Controllers/DenpyoDetailController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Royality.Application.DenpyoItems.Commands.SaveDenpyo;
using Royality.Application.DenpyoItems.Queries.GetDenpyoInfo;
using Royality.WebUI.Models;
using System.Threading.Tasks;

namespace Royality.WebUI.Controllers
{
    public class DenpyoDetailController : BaseController
    {
        #region Constructor
        public DenpyoDetailController(IMediator mediator) : base(mediator)
        {
        }
        #endregion

        public async Task<IActionResult> Index(string id)
        {
            DenDetailInfoViewModel DetailViewModel = new DenDetailInfoViewModel();

            DenpyoInfo responseDenQuery = await _mediator.Send(new GetDenpyoInfoQuery() { DenNo = id });
            DetailViewModel.DenpyoInfo = responseDenQuery;

            ///モデル　鮮度
            ///
            ///ビューを返す

            return View(DetailViewModel);
        }

        public async Task<IActionResult> Save(SaveDenpyoInfo denpyoInfo)
        {
            var resDenNo = await _mediator.Send(new SaveDenpyoCommand() { DenpyoInfo = denpyoInfo });
            return new JsonResult(new Response { Result = resDenNo });
        }
    }
}

Royality/src/WebUI/Controllers/DenpyoListController.cs
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Royality.Application.DenpyoItems.Queries.GetDenpyoInfoList;
using Royality.Application.EnumItems.Queries.GetStatusTypeList;
using Royality.Application.SiharaiSakiItems.Queries;
using Royality.Application.SiharaiSakiItems.Queries.GetSiireSakiList;
using Royality.Models;
using Royality.WebUI.Controllers;
using Royality.WebUI.Utility;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Royality.Controllers
{
    public class DenpyoListController : BaseController
    {
        #region Constructur
        public DenpyoListController(IMediator medidator) : base(medidator)
        {
        }
        #endregion


        public async Task<IActionResult> Index()
        {
            DenpyoListViewModel objViewModel = new DenpyoListViewModel();

            var responseStatusList = await _mediator.Send(new GetStatusTypeListQuery());
            objViewModel.StatusList = WebUtility.CreateSelectList(responseStatusList);

            return View(objViewModel);
        }

        /// <summary>
        /// テーブル表示用の伝票リストを取得
        /// </summary>
        /// <param name="searchData"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> GetDenpyoList([FromForm] GetDenpyoInfoListQuery searchData)
        {
            DenpyoInfoList resDenListQuery = await _mediator.Send(searchData);

            var response = new
            {
                Result = resDenListQuery.DenpyoList,
                resDenListQuery.Draw,
                resDenListQuery.RecordsTotal,
                resDenListQuery.RecordsFiltered
            };

            return new JsonResult(response);
        }
            
        public async Task<IActionResult> SiharaiSakiDlg()
        {
            List<Siharaisaki> response = await _mediator.Send(new GetSiharaiSakiListQuery());
            return PartialView("~/Views/CommonDialog/_DlgSiharaisakiList.cshtml", response);
        }
    }
}

Royality/src/WebUI/Views/CommonDialog/_DlgSiharaisakiList.cshtml
@Model IEnumerable<Siharaisaki>

    <!-- _/_/_/_/_/_/_/_/_/_/_/_/ -->
    <!-- _/  検索子画面           -->
    <!-- _/_/_/_/_/_/_/_/_/_/_/_/ -->
    <!-- 仕入先検索 -->
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span>x</span></button>
                <h4 class=" ">支払先検索</h4>
            </div>
            <div class="modal-body">
                <table class="table table-striped table-hover item_center">
                    <thead class="scrl_head">
                        <tr>
                            <th class="siharaisaki_code">支払先コード</th>
                            <th class="siharaisaki_name">支払先名</th>
                        </tr>
                    </thead>
                    <tbody class="scrl_body">
                        <!--- 支払先リスト --->
                        @foreach (var siharaisaki in Model)
                        {
                            var id = "sname_" + @siharaisaki.Code;
                            <tr onclick="siharaisaki_select('@siharaisaki.Code', '@siharaisaki.Name')">
                                <td class="siharaisaki_code">@siharaisaki.Code</td>
                                <td class="siharaisaki_name" id="@id">@siharaisaki.Name</td>
                            </tr>
                        }
                        <!--- 支払先リスト --->
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">閉じる</button>
                @*<button type="button" class="btn btn-primary">ボタン</button>*@
            </div>
        </div>
    </div>

Royality/src/WebUI/Views/DenpyoDetail/Dialog/_AutoAnbun.cshtml
<div class="container-fluid">
    <div class="row">

        <!--_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/ -->
        <!--/* _/_/_/_ モーダルExcelSheet(Left)/_/_/_/_/ -->
        <div class="col-md-6">
            <ul class="nav nav-pills">
                <li id="tabTaisyoHinban" role="presentation" class="tabTaisyoSheetLinks active" data-target="tabTaisyoHinbanSheet"><a>対象品番設定</a></li>
            </ul>

            <div id="tabTaisyoHinbanSheet" class="taisyoSheetContent">
                <table>
                    <tr>
                        <td></td>
                    </tr>
                </table>
                <div id="spreadSheetHinban" class="excelGrid"></div>
            </div>

            @*<div id="tabTaisyoHinbanSheet" class="taisyoSheetContent">
                    <div id="spreadsheetTenpo" class="excelGrid"></div>
                </div>*@

        </div>
        <!--/* _/_/_/_ モーダルExcelSheet(Left) /_/_/_/_/ -->
        <!--_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/ -->

        <!--_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/ -->
        <!--/* _/_/_/_ モーダル計算確認(rigth) /_/_/_/_/ -->
        <div class="col-md-6">
            <div class="anbunSettei">
                <div>
                    <label>按分設定</label>
                </div>

                <div class="col-xs-12">
                    <table class="item_center">
                        <tbody>
                            <tr>
                                <th style="width:100px;">
                                    <label for="date" class="control-label">伝票日付</label>
                                </th>
                                <td style="width:100px;">
                                    <input id="DenStartDate" name="DenStartDate" maxlength="8" autocomplete="off" class="form-control datepicker" />
                                </td>
                                <td style="width:40px;">
                                    <span>～</span>
                                </td>
                                <td style="width:100px;">
                                    <input id="DenEndDate" name="DenEndDate" maxlength="8" autocomplete="off" class="form-control datepicker" />
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div class="col-xs-12 denpyoKeisanBtnArea">
                    <table class="item_center">
                        <tbody>
                            <tr>
                                <th style="width:100px;">
                                </th>
                                <td>
                                    <button id="btnKeisan" style="width:100px;" type="button" class="btn btn-primary">伝票計算</button>
                                </td>
                                <td style="width:40px;">
                                </td>
                                <td>
                                    <button id="btnClearDlg" style="width:100px;" type="button" class="btn btn-default">クリア</button>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div rowspan="3"></div>
                <div class="col-xs-12">
                    <div>
                        <label>按分金額確認</label>
                        <button id="btnDownloadResultData" type="button" class="btn btn-light btn-anbunResultDL">
                            按分結果ダウンロード
                            <span class="glyphicon glyphicon-download"></span>
                        </button>
                    </div>
                </div>

                <div class="col-xs-12">
                    <section>
                        <div class="table-responsive scrollTbl">
                            <table id="tblAnbunResultUriage" class="table-bordered" cellpadding="0" cellspacing="0">
                                <colgroup>
                                    <col width="80" />
                                    <col width="140" />
                                    <col width="93" />
                                    <col width="80" />
                                </colgroup>
                                <thead class="ttl_head">
                                    <tr>
                                        <th>
                                            店番
                                        </th>
                                        <th>
                                            店名
                                        </th>
                                        <th>
                                            按分金額
                                        </th>
                                        <th>
                                            按分率
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </section>
                </div>
            </div>
        </div>
        <!--/* _/_/_/_ モーダル計算確認(rigth) /_/_/_/_/ -->
        <!--_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/ -->

    </div>
</div>

Royality/src/WebUI/Views/DenpyoDetail/Dialog/_DigHinbanTouroku.cshtml
<div class="modal-dialog modal-lg hinbanTourokuDlgModel">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"><span>x</span></button>
            <h4 class="modal-title">
                品番登録
            </h4>
            <ul class="nav nav-pills">
                <li id="tabAutoAnbun" role="presentation" class="anbunModTabLinks active" data-target="tabAutoAnbunData"><a>自動按分</a></li>
            </ul>
        </div>

        <div class="modal-body">
            <div id="tabAutoAnbunData" class="anbunModTabContent">
                <partial name="~/Views/DenpyoDetail/Dialog/_AutoAnbun.cshtml">
            </div>
        </div>

        <div class="modal-footer">
            <button id="btnAutoSet" type="button" class="btn btn-primary">自動セット</button>
            <button id="btnAnbunKeisan" type="button" class="btn btn-primary">計算</button>
            <button id="btnHinbanDialogDataDelete" type="button" class="btn btn-warning">削除</button>
            <button id="btnHinbanDlgClose" type="button" class="btn " data-dismiss="modal">閉じる</button>
        </div>
        
    </div>
</div>

Royality/src/WebUI/Views/DenpyoDetail/Index.cshtml
@model Royality.WebUI.Models.DenDetailInfoViewModel;
@{
    ViewData["Title"] = "ロイヤリティ登録";
}

<!-- _/_/_/_/_/_/_/_/_/_/_/_/ -->
<!-- _/  メニュー本体         -->
<!-- _/_/_/_/_/_/_/_/_/_/_/_/ -->
<div class="container-fluid" id="main_container">
    <div class="panel-default">
        <div class="panel-heading empHeading">
        </div>

        <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++ -->
        <!-- +                 入力一覧(Left)                   -->
        <div class="panel panel-body">
            <div class="row">
                <div class="col-md-6">
                    <table class="table table-hover table-bordered table-condensed item_center">
                        <thead class="ttl_head">
                            <tr>
                                <th class="code_wd">支払先コード</th>
                                <th>支払先名</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="code_wd col-xs-4">
                                    <div class="input-group">
                                        <input id="SiharaiSakiCode" asp-for="@Model.DenpyoInfo.SiharaiSakiCode" class="form-control numstr" />
                                        <span class="input-group-btn">
                                            <button type="button" id="btnGetSiharaiSaki" class="btn btn-info">検索</button>
                                        </span>
                                    </div>
                                </td>
                                <td class="hstr col-xs-8">
                                    <label id="SiharaiSakiNameLbl"></label>
                                </td>
                            </tr>
                        </tbody>
                    </table>

                    <div class="col-xs-4">
                        <table class="table table-hover table-bordered table-condensed item_center">
                            <thead class="ttl_head">
                                <tr>
                                    <th class="code_wd">伝票日付</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        <input id="DenHiduke" class="form-control datepicker numstr" maxlength="8" autocomplete="off" />
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    <div class="col-xs-4">
                        <table class="table table-hover table-bordered table-condensed item_center">
                            <thead class="ttl_head">
                                <tr>
                                    <th>伝票番号</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="form-group numstr denpyoNumber" data-is-new="@Model.IsNewDenpyo">
                                        @*@if (@Model.IsNewDenpyo)
                                        {
                                            <label id="DenNoLbl" style="display:none;" asp-for="@Model.DenpyoInfo.DenNo">*@
                                                <input id="DenNo" class="form-control" maxlength="10" />
                                            @*</label>*@
                                        @*}
                                        else
                                        {
                                            <label id="DenNoLbl" typeof="" asp-for="@Model.DenpyoInfo.DenNo">
                                                @Model.DenpyoInfo.DenNo
                                            </label>
                                            <Input id="DenNo" type="hidden" asp-for="@Model.DenpyoInfo.DenNo">

                                        }*@
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="col-xs-2"></div>


                    <div class="col-xs-12">
                        <table class="table table-hover table-bordered table-condensed item_center">
                            <thead class="ttl_head">
                                <tr>
                                    <th>特記事項</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td class="form-group numstr denpyoNumber">
                                        <textarea id="txtDenRemarks" placeholder="詳細を入力してください" class="form-control" name="jikou" style="height:190px;"></textarea>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <!-- +++++++++++++++++++++++++++++++++++++++ -->
                <!-- *        テーブル部門リスト(Right)    + -->
                <div class="col-md-6">
                    <section style="margin-bottom:30px;">
                        <div class="table-responsive scrollTbl">
                            <table id="detail_table" class="table table-hover table-bordered table-condensed sticky_table item_center">
                                <thead class="ttl_head">
                                    <tr>
                                        @*<th style="width: 50px;">No</th>*@
                                        <th>部門名</th>
                                        <th>金額</th>
                                    </tr>
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </section>

                    <table id="den_meisai_table_foot" class="table table-condensed item_center">
                        <tbody>
                            <tr>
                                <td class="col-xs-3" rowspan="3"></td>
                                <td class="no_frame col-xs-5" rowspan="3">
                                    <div class="input-group">
                                        <span class="input-group-addon">税率</span>
                                        <input id="DenTax" type="text" asp-for="@Model.DenpyoInfo.DenTax" class="form-control" maxlength="2" />
                                        <span class="input-group-addon">%</span>
                                    </div>
                                </td>
                                <th>小計</th>
                                <td id="Shoukei" class="td_num numstr kingaku">@Model.DenpyoInfo.Syukei</td>
                            </tr>
                            <tr>
                                <th>消費税</th>
                                <td id="Shohizei" class="td_num numstr kingaku">@Model.DenpyoInfo.Shohizei</td>
                            </tr>
                            <tr>
                                <th>合計</th>
                                <td id="Goukei" class="td_num numstr kingaku">@Model.DenpyoInfo.Goukei</td>
                            </tr>
                        </tbody>

                    </table>

                </div>

            </div>
        </div>


        <!-- +++++++++++++++++++++++++++++++++++++++ -->
        <!-- * 伝票フッター(操作ボタン)            + -->
        <div class="panel panel-footer">
            <div class="row button_area">
                <div class="col-xs-2">
                    <button id="btnHinbanToroku" type="button" class="btn btn-default form-control">
                        品番設定・按分登録
                    </button>
                </div>
                <div class="col-xs-2">
                    <label class="footerlabel">
                        登録済品番数：<span id="lblHinbanCount">@Model.HinbanCount</span>
                    </label>
                </div>
                <div class="col-xs-2">
                    <label class="footerlabel">
                        按分設定: <span id="lblAnbunResult">
                            @{ @Html.Raw(Model.IsAnbunResultSet == true ? "済" : "未");}
                        </span>
                    </label>
                </div>
                <div class="col-xs-2"></div>
                <div class="col-xs-1">
                    <button id="btnNew" type="button" class="btn btn-success form-control">新規作成</button>
                </div>
                <div class="col-xs-1">
                    <button id="btnSave" type="button" class="btn btn-primary form-control">保存</button>
                </div>
                <div class="col-xs-1">
                    <button id="btnDelete" type="button" class="btn btn-warning form-control">削除</button>
                </div>
                <div class="col-xs-1">
                    <button id="btnFix" type="button" class="btn btn-danger form-control">確定</button>
                </div>
            </div>
        </div>
        <!-- * 伝票フッター(操作ボタン)            + -->
        <!-- +++++++++++++++++++++++++++++++++++++++ -->

        <div id="overlay" class="overlay" style="display:none;">
            <div class="spinner"></div>
            <br />
            <div class="overlayMessage"></div>
        </div>
    </div>

    <!-- 支払先検索 START -->
    <div class="modal fade" id="siharaisaki_search" role="dialog" data-url="@Url.Action("SiharaiSakiDlg", "DenpyoList")" tabindex="-1"></div>
    <!-- 支払先検索 END -->
    <!-- 品番登録・按分設定 START-->
    <div class="modal fade hinbanTouroku" id="hinban_touroku" role="dialog" data-url="@Url.Action("Index","HinbanTourokuDialog")" data-backdrop="static" data-keyboard="false" tabindex="-1"></div>
    <!-- 品番登録・按分設定 END-->


    @section Styles
    {
        <link type="text/css" rel="stylesheet" href="~/lib/Jexcel/css/jsuites.css" />
        <link type="text/css" rel="stylesheet" href="~/lib/Jexcel/css/jexcel.css" />

        <environment include="Development">
            <link type="text/css" rel="stylesheet" href="~/css/denpyo_detail.css" />
            <link type="text/css" rel="stylesheet" href="~/css/hinban_touroku_dlg.css" />
        </environment>
    }

    @section Scripts
    {
        <script type="text/javascript" src="~/lib/Jexcel/js/jsuites.js"></script>
        <script type="text/javascript" src="~/lib/Jexcel/js/jexcel.js"></script>

        <environment include="Development">
            <script type="module" src="~/scripts/build/denpyo_Detail.js"></script>
            <script type="module" src="~/scripts/build/hinban_touroku.js"></script>
        </environment>
    }
</div>

Royality/src/WebUI/Views/DenpyoList/Index.cshtml
@model DenpyoListViewModel;

@{
    ViewData["Title"] = "ロイヤリティ登録";
}

<!-- _/_/_/_/_/_/_/_/_/_/_/_/ -->
<!-- _/  メニュー本体         -->
<!-- _/_/_/_/_/_/_/_/_/_/_/_/ -->
<div class="container-fluid" id="main_container">
    <div class="panel panel-default">
        <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++ -->
        <!-- +  検索条件領域                                    -->
        <div class="panel-heading">
            <table class="item_center">
                <tbody>
                    <tr>
                        <th class="search1">
                            <label for="date" class="control-label">伝票日付</label>
                        </th>
                        <td class="search1">
                            <input id="DenStartDate" name="DenStartDate" maxlength="8" autocomplete="off" class="form-control datepicker" />
                        </td>
                        <td class="search2">
                            ～
                        </td>
                        <td class="search1">
                            <input id="DenEndDate" name="DenEndDate" maxlength="8" autocomplete="off" class="form-control datepicker" />
                        </td>
                        <th class="search1">
                            処理状況
                        </th>
                        <td class="search1">
                            <select class="form-control" id="StatusID" name="StatusID" asp-items="@Model.StatusList">
                            </select>
                        </td>

                        <th class="search3">
                            支払い先
                        </th>
                        <td class="search4">
                            <div class="input-group">
                                <input id="SiharaiSakiCode" name="SiharaiSakiCode" class="form-control" maxlength="6" />
                                <span class="input-group-btn">
                                    <button type="button" id="btnGetSiharaiSaki" class="btn btn-info">検索</button>
                                </span>
                            </div>
                        </td>
                        <td class="search5" colspan="2">
                            <label id="SiharaiSakiNameLbl" name="SiharaiSakiName"></label>
                        </td>
                        <td>&nbsp;</td>
                        <td>
                            <button class="btn btn-default form-control" id="btnSearchClear">条件クリア</button>
                        </td>
                        <td>
                            <button class="btn btn-info form-control" id="btnSearch">検索</button>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div id="Message" class="col-xs-12" style="margin-top:10px;display:none;"></div>

        <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++ -->
        <!-- +                 申請一覧                         -->
        <div id="denpyo_list">
            <partial name="_DenpyoList" />
        </div>


        <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++ -->
        <!-- +          伝票フッター（操作ボタン）              -->
        <div class="panel-footer">
            <div class="row button_area">
                <div class="col-xs-9"></div>
                <div class="col-xs-1">
                    <button id="btn-new" type="button" class="btn btn-success form-control"
                            onclick="window.location.href = '@Url.Action("Index", "DenpyoDetail")';">
                        新規作成
                    </button>
                </div>
                <div class="col-xs-1">
                    <button id="btnDelete" type="button" class="btn btn-warning form-control">削除</button>
                </div>
                <div class="col-xs-1">
                    <button id="btnKakutei" type="button" class="btn btn-danger form-control">確定</button>
                </div>
            </div>
        </div>
        <!--            * 伝票フッター(操作ボタン)            + -->
        <!-- ++++++++++++++++++++++++++++++++++++++++++++++++++ -->
    </div>
    <div id="overlay" class="overlay" style="display:none;">
        <div class="spinner"></div>
        <br />
        <div class="overlayMessage"></div>
    </div>
</div>

<!-- 支払先検索 START -->
<div class="modal fade" id="siharaisaki_search" role="dialog" data-url="@Url.Action("SiharaiSakiDlg", "DenpyoList")" tabindex="-1"></div>
<!-- 支払先検索 END -->

<!-- _/_/_/_/_/_/_/_/_/_/_/_/ -->
<!-- _/  メニュー本体 終了    -->
<!-- _/_/_/_/_/_/_/_/_/_/_/_/ -->

@section Styles
{
    <environment include="Development">
        <link type="text/css" rel="stylesheet" href="~/css/denpyo_list.css" />
    </environment>
}
@section Scripts
{
    <environment include="Development">
        <script type="text/javascript" src="~/scripts/build/denpyo_list.js"></script>
    </environment>
}

Royality/src/WebUI/Views/DenpyoList/_DenpyoList.cshtml
<!-- ++++++++++++++++++++++++++++++++++++++++++++++++++ -->
<!-- +                 申請一覧                         -->
<div class="panel panel-body" id="list_area">
    <table id="sinsei_table" class="table-bordered">
        <thead class="ttl_head">
            <tr>
                <th>
                    <input id="chkCheckAll" type="checkbox" name="CHK_ALL " />
                </th>
                <th>伝票番号</th>
                <th>伝票日付</th>
                <th>支払先</th>
                <th>支払先名</th>
                @*<th>丸め</th>
                <th>単位</th>*@
                <th>小計</th>
                <th>消費税</th>
                <th>合計</th>
                <th>最終更新者</th>
                <th>最終更新日</th>
                <th>処理状況</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

Royality/src/WebUI/Views/Shared/_Constants.cshtml
@using Royality.WebUI.Utility

<script type="text/javascript">
    const SIHARAISAKI_NOT_RECORD = "支払先コードが入力されていません。";
    const SHOULD_ZERO_ALLOWED = "0の値を税率に設定します。よろしいですか。";
</script>